[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_eol = LF
upload_speed = 115200
upload_port = COM8
monitor_port = COM8
lib_deps =
  arduino-irremote/IRremote@4.7.1
